spring:
  application:
    name: blog
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:file:.env[.properties]

security:
  jwt:
    key: 9950d5009b26fb01ee90ca6c8ba8fb165173c003b6d49fc9ff9a8852033e93b9s
    expiration-time: 3600000
    refresh-token:
      expiration-ms: 7776000000

logging:
  level:
    com.regisx001: INFO

file:
  upload-dir:
    uploads: /uploads
